import type { Metadata } from "next";
import { Geist_Mono, Yeseva_One } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const yesevaOne = Yeseva_One({
  variable: "--font-yeseva-one",
  weight: "400",
  subsets: ["latin", "cyrillic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${yesevaOne.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
